/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartographieRouteImport } from './routes/cartographie'
import { Route as ConformiteRouteImport } from './routes/conformite'
import { Route as GraphiquesRouteImport } from './routes/graphiques'
import { Route as IndicesRouteImport } from './routes/indices'
import { Route as RapportRouteImport } from './routes/rapport'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as TableauDeBordRouteImport } from './routes/tableau-de-bord'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartographieRoute = CartographieRouteImport.update({
  id: '/cartographie',
  path: '/cartographie',
  getParentRoute: () => rootRouteImport,
} as any)
const ConformiteRoute = ConformiteRouteImport.update({
  id: '/conformite',
  path: '/conformite',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphiquesRoute = GraphiquesRouteImport.update({
  id: '/graphiques',
  path: '/graphiques',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicesRoute = IndicesRouteImport.update({
  id: '/indices',
  path: '/indices',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportRoute = RapportRouteImport.update({
  id: '/rapport',
  path: '/rapport',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const TableauDeBordRoute = TableauDeBordRouteImport.update({
  id: '/tableau-de-bord',
  path: '/tableau-de-bord',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cartographie': typeof CartographieRoute
  '/conformite': typeof ConformiteRoute
  '/graphiques': typeof GraphiquesRoute
  '/indices': typeof IndicesRoute
  '/rapport': typeof RapportRoute
  '/references': typeof ReferencesRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cartographie': typeof CartographieRoute
  '/conformite': typeof ConformiteRoute
  '/graphiques': typeof GraphiquesRoute
  '/indices': typeof IndicesRoute
  '/rapport': typeof RapportRoute
  '/references': typeof ReferencesRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cartographie': typeof CartographieRoute
  '/conformite': typeof ConformiteRoute
  '/graphiques': typeof GraphiquesRoute
  '/indices': typeof IndicesRoute
  '/rapport': typeof RapportRoute
  '/references': typeof ReferencesRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cartographie'
    | '/conformite'
    | '/graphiques'
    | '/indices'
    | '/rapport'
    | '/references'
    | '/tableau-de-bord'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cartographie'
    | '/conformite'
    | '/graphiques'
    | '/indices'
    | '/rapport'
    | '/references'
    | '/tableau-de-bord'
  id:
    | '__root__'
    | '/'
    | '/cartographie'
    | '/conformite'
    | '/graphiques'
    | '/indices'
    | '/rapport'
    | '/references'
    | '/tableau-de-bord'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartographieRoute: typeof CartographieRoute
  ConformiteRoute: typeof ConformiteRoute
  GraphiquesRoute: typeof GraphiquesRoute
  IndicesRoute: typeof IndicesRoute
  RapportRoute: typeof RapportRoute
  ReferencesRoute: typeof ReferencesRoute
  TableauDeBordRoute: typeof TableauDeBordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartographie': {
      id: '/cartographie'
      path: '/cartographie'
      fullPath: '/cartographie'
      preLoaderRoute: typeof CartographieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conformite': {
      id: '/conformite'
      path: '/conformite'
      fullPath: '/conformite'
      preLoaderRoute: typeof ConformiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphiques': {
      id: '/graphiques'
      path: '/graphiques'
      fullPath: '/graphiques'
      preLoaderRoute: typeof GraphiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indices': {
      id: '/indices'
      path: '/indices'
      fullPath: '/indices'
      preLoaderRoute: typeof IndicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapport': {
      id: '/rapport'
      path: '/rapport'
      fullPath: '/rapport'
      preLoaderRoute: typeof RapportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableau-de-bord': {
      id: '/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof TableauDeBordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartographieRoute: CartographieRoute,
  ConformiteRoute: ConformiteRoute,
  GraphiquesRoute: GraphiquesRoute,
  IndicesRoute: IndicesRoute,
  RapportRoute: RapportRoute,
  ReferencesRoute: ReferencesRoute,
  TableauDeBordRoute: TableauDeBordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
